Repository CodeChain-io/codechain, pull requests merged in 2019-10, with the labels that each got.

#1803 Extract the crypto module to a new repository
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  crypto/Cargo.toml
  crypto/src/aes.rs
  crypto/src/blake.rs
  crypto/src/error.rs
  crypto/src/hash.rs
  crypto/src/lib.rs
  crypto/src/password.rs
  crypto/src/pbkdf2.rs
  crypto/src/scrypt.rs
  discovery/Cargo.toml
  key/Cargo.toml
  keystore/Cargo.toml
  network/Cargo.toml
  rpc/Cargo.toml
  state/Cargo.toml
  stratum/Cargo.toml
  types/Cargo.toml
  util/journaldb/Cargo.toml
  util/memorydb/Cargo.toml
  util/merkle/Cargo.toml
  util/trie-standardmap/Cargo.toml
  vm/Cargo.toml
Labels: refactoring

#1807 Do not generate a seal if the block is generated from a past view
  core/src/consensus/tendermint/worker.rs
Labels: bug, consensus

#1813 Enable all grandchild of the best block to become a best proposal block
  core/src/blockchain/blockchain.rs
  core/src/blockchain/headerchain.rs
  core/src/consensus/mod.rs
  core/src/consensus/tendermint/engine.rs
Labels: bug, consensus

#1825 Update README to correspond to rust toolchains
  README.md
Labels: documentation

#1834 Make functions in tendermint/worker.rs that are not used outside private
  core/src/consensus/tendermint/worker.rs
Labels: refactoring

#1836 Remove BLKNUM from the CCVM spec
  spec/CodeChain-Virtual-Machine.md
Labels: documentation
