Repository CodeChain-io/codechain, pull requests merged in 2019-04, with the labels that each got.

#1426 Fix the logic to distribute transaction fee
  core/src/consensus/tendermint/engine.rs
  test/src/e2e.long/staking.test.ts
  test/src/scheme/tendermint-int.json
Labels: consensus, transaction

#1433 Add a scheme file for the mainnet
  codechain/config/chain_type.rs
  codechain/config/presets/config.prod.toml
  core/res/mainnet.json
  core/src/scheme/scheme.rs
Labels: scheme

#1427 Move the setup part from docs to README.md
  README.md
  docs/setup.rst
Labels: documentation

#1436 Fix broken markdown format
  README.md
Labels: documentation

#1439 Remove empty stake entries from state
  core/src/consensus/tendermint/stake/action_data.rs
  core/src/consensus/tendermint/stake/mod.rs
  state/src/cache/top_cache.rs
  state/src/impls/top_level.rs
  state/src/traits.rs
  test/src/e2e.long/staking.test.ts
Labels: state

#1438 Fix reversed delegator-delegatee variable names in test
  core/src/consensus/tendermint/stake/action_data.rs
Labels: refactoring, test

#1437 Skip Travis when only markdown files are changed
  .travis.yml
Labels: test

#1423 Add spec for the minimum fee
  spec/Minimum-Fee.md
  spec/Transaction.md
Labels: documentation

#1446 Add a test to check whether it allows zero pay transaction
  test/src/e2e.long/transactions.test.ts
Labels: test

#1447 Use "mainnet" as a default chain in the account subcommand
  codechain/subcommand/account_command.rs
Labels: cli

#1448 Fix not to include zero-valued entry in delegation
  core/src/consensus/tendermint/stake/action_data.rs
Labels: consensus, state

#1454 Fix travis check change and improve the debugability of the shell script
  .travis.yml
  .travis/check-change
Labels: test

#1458 Remove "husky" and "saluki" from documents
  codechain/codechain.yml
  spec/JSON-RPC.md
Labels: documentation

#1455 Add current_block_timestamp to State::apply
  core/src/block.rs
  state/src/impls/top_level.rs
Labels: refactoring, transaction

#1444 Add "Connect to the existing network" section in the manual
  docs/basic-usage.rst
Labels: documentation

#1461 Split e2e tests for transactions to multiple files
  test/src/e2e.long/transactions.test.ts
  test/src/e2e/burn.test.ts
  test/src/e2e/changeAssetScheme.test.ts
  test/src/e2e/increaseAssetSupply.test.ts
  test/src/e2e/mintAsset.test.ts
  test/src/e2e/partialSignature.test.ts
  test/src/e2e/pay.test.ts
  test/src/e2e/transferAsset.test.ts
  test/src/e2e/unwrap.test.ts
  test/src/e2e/wrap.test.ts
Labels: test

#1462 Cleanup the imports in e2e tests
  test/src/e2e.long/bootstrap.test.ts
  test/src/e2e.long/expiration.test.ts
  test/src/e2e.long/invalidBlockPropagation0.test.ts
  test/src/e2e.long/invalidBlockPropagation1.test.ts
  test/src/e2e.long/invalidBlockPropagation2.test.ts
  test/src/e2e.long/invalidBlockPropagation3.test.ts
  test/src/e2e.long/invalidBlockPropagation4.test.ts
  test/src/e2e.long/invalidBlockPropagation5.test.ts
  test/src/e2e.long/invalidBlockPropagation6.test.ts
  test/src/e2e.long/invalidBlockPropagation8.test.ts
  test/src/e2e.long/invalidBlockPropagation9.test.ts
  test/src/e2e.long/mempool.test.ts
  test/src/e2e.long/onChainBlockValid.test.ts
  test/src/e2e.long/orders.test.ts
  test/src/e2e.long/staking.test.ts
  test/src/e2e.long/tendermint.test.ts
  test/src/e2e.long/timelock.test.ts
  test/src/e2e/chain.test.ts
  test/src/e2e/customAction.test.ts
  test/src/e2e/engine.test.ts
  test/src/e2e/regularkey.test.ts
  test/src/e2e/storeRemove.test.ts
  test/src/e2e/transactionResult.test.ts
  test/src/helper/chai-similar.test.ts
  test/src/helper/chai-similar.ts
  test/src/helper/mock/blockSyncMessage.ts
  test/src/helper/mock/cHeader.ts
  test/src/helper/mock/index.ts
  test/src/helper/mock/test/blockSyncMessage.test.ts
  test/src/helper/mock/test/message.test.ts
  test/src/helper/mock/test/txSyncMessage.test.ts
  test/src/helper/mock/transactionSyncMessage.ts
Labels: test

#1451 Implement chain_getMinTransactionFee rpc
  rpc/src/v1/impls/chain.rs
  rpc/src/v1/traits/chain.rs
Labels: rpc

#1465 Fix a typo in the codechain.yml file
  codechain/codechain.yml
Labels: cli, documentation

#1468 Do not request the next headers if the pivot score is not changed
  sync/src/block/downloader/header.rs
  sync/src/block/extension.rs
Labels: sync

#1471 Make net_recentNetworkUsage show the destination address
  codechain/dummy_network_service.rs
  network/src/control.rs
  network/src/p2p/handler.rs
  network/src/service.rs
  rpc/src/v1/impls/net.rs
  rpc/src/v1/traits/net.rs
Labels: network, rpc

#1472 Use best_proposal_block_hash in the sync extension
  core/src/blockchain/blockchain.rs
  core/src/blockchain_info.rs
  core/src/client/test_client.rs
  sync/src/block/extension.rs
Labels: sync

#1479 Enhance tests about payment transaction
  test/src/e2e/pay.test.ts
Labels: test, transaction

#1476 Allow struct/array to overflow
  core/src/client/importer.rs
  core/src/consensus/tendermint/worker.rs
  core/src/miner/mem_pool.rs
  core/src/miner/work_notify.rs
  json/src/hash.rs
  json/src/uint.rs
  keystore/tests/api.rs
  rustfmt.toml
  state/src/impls/top_level.rs
  types/src/transaction/shard.rs
  types/src/util/tag.rs
  util/io/src/service.rs
  util/rlp/tests/tests.rs
  util/secp256k1/src/key.rs
Labels: build

#1473 Disable CustomAction DelegateCCS
  core/src/consensus/tendermint/stake/mod.rs
  test/src/e2e.long/staking.test.ts
  test/src/helper/spawn.ts
Labels: transaction

#1480 Send header request to a random peer at every timeout
  sync/src/block/extension.rs
Labels: sync

#1484 Move docs to a new repo
  docs/.gitattributes
  docs/.gitignore
  docs/Makefile
  docs/account-management.rst
  docs/asset-management-by-example.rst
  docs/basic-usage.rst
  docs/blakepow.rst
  docs/codechain-coin.rst
  docs/community.rst
  docs/conf.py
  docs/configuration.rst
  docs/consensus-algorithms.rst
  docs/contributors.rst
  docs/cuckoo.rst
  docs/frequently-asked-questions.rst
  docs/gateway.rst
  docs/glossary.rst
  docs/how-to-configure.rst
  docs/index.rst
  docs/introduction.rst
  docs/learn-more-about-codechain.rst
  docs/lock-script.rst
  docs/logging.rst
  docs/make.bat
  docs/requirements.txt
  docs/script-order.png
  docs/security.rst
  docs/solo.rst
  docs/tendermint.rst
  docs/transaction.rst
  docs/transactions.rst
  docs/under_construction.jpg
  docs/utxo-transaction.png
  docs/what-features-does-codechain-offer.rst
  docs/what-is-codechain.rst
  docs/what-is-utxo.rst
Labels: documentation

#1478 Update pivot to the best_header if the best_header is already imported
  sync/src/block/downloader/header.rs
Labels: sync

#1488 Remove docs/ directory from travis skip check
  .travis.yml
Labels: test

#1466 Add spec about chain_getMinTransactionFee
  spec/JSON-RPC.md
Labels: documentation, rpc

#1490 Update timelock spec to use the next script byte
  spec/CodeChain-Virtual-Machine.md
Labels: documentation, script

#1494 Fix .dockerignore file to get commit hash successfully from docker image clients.
  .dockerignore
Labels: build
