Repository CodeChain-io/codechain, pull requests merged in 2019-08, with the labels that each got.

#1736 Assert that transaction is executed in the expected term
  test/src/e2e.dynval/1/dv.m-m'.test.ts
  test/src/e2e.dynval/setup.ts
Labels: test

#1495 Remove the cli optional argument "no-miner"
  codechain/codechain.yml
  codechain/config/mod.rs
  codechain/config/presets/config.dev.toml
  codechain/config/presets/config.prod.toml
  codechain/run_node.rs
Labels: do-not-merge

#1749 Fix a memory leak in header downloader's downloaded
  sync/src/block/downloader/header.rs
Labels: bug, sync

#1750 Do not request older headers if re-organization is not occurred
  sync/src/block/downloader/header.rs
Labels: bug, sync

#1755 Replace hashmap cache to LRU cache
  Cargo.lock
  core/Cargo.toml
  core/src/blockchain/body_db.rs
  core/src/blockchain/headerchain.rs
  core/src/lib.rs
Labels: sync

#1753 Supress header download when queue is full
  sync/src/block/downloader/header.rs
Labels: network

#1747 Update dynamic validator docs
  spec/Dynamic-Validator.md
  spec/Staking.md
Labels: documentation

#1756 Update tendermint timeouts of the Main network
  core/res/mainnet.json
Labels: consensus
