Repository CodeChain-io/codechain, pull requests merged in 2019-05, with the labels that each got.

#1510 Remove impl RlpEncodable/Decodable for i32/i64
  util/rlp/src/impls.rs
  util/rlp/src/stream.rs
  util/rlp/src/untrusted_rlp.rs
  util/rlp/tests/tests.rs
Labels: util

#1079 Enable TimerLoop to be dropped
  util/timer/src/timer.rs
Labels: util

#1509 [WIP] Document the spec of dynamic validators
  spec/Dynamic-Validator.md
Labels: consensus, do-not-merge, documentation

#1518 Do not set the "best header" to a header that has a lower number than before
  core/src/blockchain/headerchain.rs
Labels: bug

#1496 Remove Reactor
  Cargo.lock
  Cargo.toml
  codechain/main.rs
  codechain/run_node.rs
  util/reactor/Cargo.toml
  util/reactor/src/lib.rs
Labels: refactoring

#1499 Add base-path option to the codechin cli arguments
  codechain/codechain.yml
  codechain/config/mod.rs
  codechain/config/presets/config.dev.toml
  codechain/config/presets/config.prod.toml
  codechain/constants.rs
  codechain/run_node.rs
Labels: cli

#1520 Update dynamic validator specification.
  spec/Dynamic-Validator.md
Labels: documentation

#1521 Fix some typos
  spec/Dynamic-Validator.md
Labels: documentation

#1523 Describe the delegation threshold
  spec/Dynamic-Validator.md
Labels: documentation

#1526 Reduce booting time by using is_empty method
  core/src/scheme/scheme.rs
  util/hashdb/src/lib.rs
  util/journaldb/src/archivedb.rs
  util/journaldb/src/traits.rs
  util/memorydb/src/lib.rs
Labels: refactoring

#1528 Fix documentation
  spec/Dynamic-Validator.md
Labels: documentation

#1532 Refine common_params.rs
  core/src/scheme/common_params.rs
Labels: refactoring

#1531 Verify the custom action on syntax check
  core/src/consensus/mod.rs
  core/src/consensus/stake/mod.rs
  rpc/src/v1/errors.rs
  rpc/src/v1/impls/engine.rs
  state/src/action_handler/hit.rs
  state/src/action_handler/mod.rs
  test/src/e2e/customAction.test.ts
  types/src/errors/syntax_error.rs
Labels: transaction

#1534 Remove the Withdraw transaction
  spec/Dynamic-Validator.md
Labels: documentation

#1539 Refine the notify interface
  core/src/client/client.rs
  core/src/client/importer.rs
Labels: refactoring

#1533 Use Rust 1.34.2 instead of 1.34.0
  .travis.yml
  rust-toolchain
Labels: build

#1512 Do not prevote to the block with irrelevant generation time
  codechain/codechain.yml
  codechain/config/mod.rs
  codechain/config/presets/config.dev.toml
  codechain/config/presets/config.prod.toml
  codechain/run_node.rs
  core/src/consensus/mod.rs
  core/src/consensus/tendermint/engine.rs
  core/src/consensus/tendermint/mod.rs
  core/src/consensus/tendermint/params.rs
  core/src/consensus/tendermint/worker.rs
  core/src/lib.rs
  json/src/scheme/tendermint.rs
Labels: consensus

#1542 Increase the number of blocks and headers to import in a round
  core/src/client/importer.rs
Labels: performance

#1545 Use the child of the best header to verify transactions
  core/src/block.rs
  core/src/header.rs
  core/src/miner/miner.rs
  test/src/e2e.long/expiration.test.ts
Labels: verification

#1530 Add spec for ChangeParameters
  spec/Staking.md
Labels: documentation

#1550 Specify the states of the dynamic validator implementation
  spec/Dynamic-Validator.md
Labels: documentation

#1549 Fix chain_getMinTransactionFee to take null as the block number
  rpc/src/v1/impls/chain.rs
  rpc/src/v1/traits/chain.rs
Labels: rpc

#1554 Change the stakeholders in solo e2e tests scheme
  test/src/e2e.long/reward2.test.ts
  test/src/e2e/reward.test.ts
  test/src/e2e/staking.test.ts
  test/src/scheme/solo-block-reward-50.json
Labels: test

#1556 Change scripts to create a docker image
  docker/ubuntu/Dockerfile
Labels: build

#1503 Add an explanation for managing data persistent
  README.md
Labels: cli, documentation

#1535 Implement ChangeParams
  core/src/consensus/stake/actions.rs
  core/src/consensus/stake/mod.rs
  spec/Staking.md
  state/src/impls/top_level.rs
  state/src/item/metadata.rs
  state/src/traits.rs
  test/src/e2e/changeParams.test.ts
  test/src/helper/spawn.ts
  types/src/errors/runtime_error.rs
Labels: transaction

#1568 Refine the interface of ValidatorList
  core/src/consensus/validator_set/mod.rs
  core/src/consensus/validator_set/null_validator.rs
  core/src/consensus/validator_set/validator_list.rs
Labels: refactoring

#1563 No need to fnd the merge base to check change
  .travis/check-change
Labels: build

#1573 Change the spec to store the public key of candidate instead of the address
  spec/Dynamic-Validator.md
Labels: consensus, documentation

#1577 Upgrade snappy to 6.2.2 to support Node 12
  test/package.json
  test/yarn.lock
Labels: test

#1572 Upgrade packages for e2e tests
  test/package.json
  test/src/e2e/network2.test.ts
  test/src/helper/mock/p2pLayer.ts
  test/src/helper/spawn.ts
  test/tsconfig.json
  test/yarn.lock
Labels: test

#1560 Change the specificaiton of ChangeParams
  spec/Staking.md
Labels: documentation, transaction

#1564 Change the way of sorting validators when giving additional rewards
  spec/Dynamic-Validator.md
Labels: documentation

#1581 Update e2e tests in rc-1.4.0
  test/package.json
  test/src/e2e/network2.test.ts
  test/src/helper/mock/p2pLayer.ts
  test/src/helper/spawn.ts
  test/tsconfig.json
  test/yarn.lock
Labels: test

#1562 Change spec to use criminal's incomes as additional rewards
  spec/Dynamic-Validator.md
Labels: documentation

#1588 Enable delegations always
  core/src/consensus/stake/mod.rs
  test/src/e2e.long/staking.test.ts
  test/src/helper/spawn.ts
Labels: consensus

#1587 Store the public key of candidates instead of the address
  core/src/consensus/stake/action_data.rs
  core/src/consensus/stake/mod.rs
  state/src/action_handler/hit.rs
  state/src/action_handler/mod.rs
  state/src/impls/top_level.rs
Labels: consensus
