Repository CodeChain-io/codechain, pull requests merged in 2019-09, with the labels that each got.

#1760 Update the best block when best proposal header is updated
  core/src/client/importer.rs
Labels: bug

#1771 Move to Commit state if enough precommits are collected
  core/src/consensus/tendermint/types.rs
  core/src/consensus/tendermint/worker.rs
Labels: consensus

#1772 Fix a step regression bug in Tendermint::worker::new_blocks
  core/src/consensus/tendermint/worker.rs
Labels: bug

#1774 Fix possible regression issue caused by `ProposeWaitEmptyBlockTimer`
  core/src/consensus/tendermint/worker.rs
Labels: bug

#1786 Import following downloaded blocks if the preceding block is already queued
  sync/src/block/extension.rs
Labels: bug, sync

#1782 Remove order
  core/src/codechain_machine.rs
  core/src/miner/mem_pool.rs
  core/src/transaction.rs
  rpc/src/v1/impls/devel.rs
  rpc/src/v1/types/action.rs
  rpc/src/v1/types/asset.rs
  rpc/src/v1/types/mod.rs
  rpc/src/v1/types/order.rs
  spec/Asset-Exchange-Protocol.md
  spec/JSON-RPC.md
  spec/Transaction.md
  state/src/impls/shard_level.rs
  state/src/impls/test_helper.rs
  state/src/impls/top_level.rs
  state/src/item/asset.rs
  test/src/e2e.long/orders.test.ts
  test/src/e2e.long/ordersDisabled.test.ts
  test/src/helper/error.ts
  types/src/errors/history_error.rs
  types/src/errors/runtime_error.rs
  types/src/errors/syntax_error.rs
  types/src/transaction/action.rs
  types/src/transaction/mod.rs
  types/src/transaction/order.rs
  types/src/transaction/shard.rs
  vm/tests/chk_multi_sig.rs
  vm/tests/chk_sig.rs
  vm/tests/executor.rs
Labels: transaction

#1784 Do not convert to Bytes until it is necessary
  core/src/consensus/tendermint/worker.rs
Labels: refactoring

#1792 Stop generating blocks if the consensus cannot make a seal
  core/src/miner/miner.rs
Labels: bug

#1801 Fix assertions to clarify the intention
  core/src/consensus/tendermint/vote_regression_checker.rs
Labels: refactoring
