Repository CodeChain-io/codechain, pull requests merged in 2020-01, with the labels that each got.

#1943 Export trie-standardmap
  Cargo.lock
  sync/Cargo.toml
  util/merkle/Cargo.toml
  util/trie-standardmap/Cargo.toml
  util/trie-standardmap/src/lib.rs
Labels: util

#1941 Add an RPC deleteAllPendingTransactions()
  core/src/client/client.rs
  core/src/client/mod.rs
  core/src/client/test_client.rs
  core/src/miner/mem_pool.rs
  core/src/miner/miner.rs
  rpc/src/v1/impls/mempool.rs
  rpc/src/v1/traits/mempool.rs
  test/src/e2e/mempool.test.ts
Labels: rpc

#1947 Export the codechain-merkle module to the merkle-trie package
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  core/src/block.rs
  core/src/client/client.rs
  core/src/client/mod.rs
  core/src/client/test_client.rs
  core/src/error.rs
  core/src/lib.rs
  core/src/scheme/scheme.rs
  core/src/verification/verification.rs
  state/Cargo.toml
  state/src/cache/shard_cache.rs
  state/src/cache/top_cache.rs
  state/src/cache/write_back.rs
  state/src/error.rs
  state/src/impls/shard_level.rs
  state/src/impls/top_level.rs
  state/src/lib.rs
  state/src/tests.rs
  state/src/traits.rs
  sync/Cargo.toml
  sync/src/lib.rs
  sync/src/snapshot/snapshot.rs
  util/merkle/Cargo.toml
  util/merkle/benches/triedb.rs
  util/merkle/src/lib.rs
  util/merkle/src/nibbleslice.rs
  util/merkle/src/node.rs
  util/merkle/src/skewed.rs
  util/merkle/src/triedb.rs
  util/merkle/src/triedbmut.rs
  util/merkle/src/triehash.rs
Labels: util

#1951 Upgrade Rust to 1.40.0
  .github/workflows/build.yml
  .github/workflows/cargo-test.yml
  .travis.yml
  README.md
  rust-toolchain
Labels: build

#1939 Convert constants to discriminated enum
  core/src/consensus/stake/actions.rs
  core/src/consensus/tendermint/message.rs
  sync/src/block/message/mod.rs
  sync/src/block/message/request.rs
  sync/src/block/message/response.rs
  types/src/errors/history_error.rs
  types/src/errors/runtime_error.rs
  types/src/errors/syntax_error.rs
  types/src/transaction/shard.rs
  vm/src/decoder.rs
  vm/src/executor.rs
  vm/src/instruction.rs
  vm/src/lib.rs
  vm/tests/executor.rs
Labels: refactoring

#1954 Add "install `cmake` to build CodeChain" in README.md and Dockerfile
  README.md
  docker/ubuntu/Dockerfile
Labels: documentation, foundry

#1952 Update JSON-RPC.md with the new RPC 'mempool_deleteAllPendingTransactions()'
  spec/JSON-RPC.md
Labels: documentation

#1955 Correct a mistake that was made while reading the mem-pool-fee-bump-shift configuration
  codechain/config/mod.rs
Labels: bug

#1958 Do not mark the block having invalid transactions root as bad
  sync/src/block/downloader/body.rs
  sync/src/block/extension.rs
Labels: bug
